USE [master]
GO

/****** Object:  Database [CIS655_Akutsu_Y]    Script Date: 3/21/2021 1:13:52 PM ******/
CREATE DATABASE [CIS655_Akutsu_Y]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CIS655_Akutsu_Y', FILENAME = N'S:\SQLData\MSSQL15.CIS655\MSSQL\Data\CIS655_Akutsu_Y.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'CIS655_Akutsu_Y_log', FILENAME = N'L:\SQLLogs\MSSQL15.CIS655\MSSQL\Logs\CIS655_Akutsu_Y_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CIS655_Akutsu_Y].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET ARITHABORT OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET  MULTI_USER 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CIS655_Akutsu_Y] SET  READ_WRITE 
GO